"""initial postgres

Revision ID: 0bfb7b02b6de
Revises: 
Create Date: 2026-03-23 17:09:43.883104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfb7b02b6de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('hr_contact', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.Enum('Pending', 'Approved', 'Rejected', name='company_approval_status'), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('usn', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('resume', sa.String(length=200), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usn')
    )
    op.create_table('placement_drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.String(length=200), nullable=True),
    sa.Column('min_cgpa', sa.Float(), nullable=True),
    sa.Column('eligible_branches', sa.String(length=200), nullable=True),
    sa.Column('eligible_batches', sa.String(length=100), nullable=True),
    sa.Column('salary_package', sa.String(length=50), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=False),
    sa.Column('drive_date', sa.Date(), nullable=False),
    sa.Column('approval_status', sa.Enum('Pending', 'Approved', 'Rejected', 'Closed', name='drive_approval_status'), nullable=False),
    sa.Column('date_rejected', sa.Boolean(), nullable=True),
    sa.Column('date_rejection_note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Applied', 'Cancelled', 'Selected', 'Rejected', name='application_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'drive_id', name='unique_student_application')
    )
    op.create_table('placement_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('package', sa.String(length=70), nullable=True),
    sa.Column('recruited_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_stats')
    op.drop_table('applications')
    op.drop_table('placement_drives')
    op.drop_table('students')
    op.drop_table('companies')
    op.drop_table('admin')
    # ### end Alembic commands ###
